Applying AVIRM style settings...

OBJ: TStyle	AVIRM	AVIRM style : 0 at: 0x55da4bd7ae90

Processing Etude_Potentiel_Ionisation_Pos_Pic_Devellopement_Os.C...

[1mRooFit v3.60 -- Developed by Wouter Verkerke and David Kirkby[0m 
                Copyright (C) 2000-2013 NIKHEF, University of California & Stanford University
                All rights reserved, please read http://roofit.sourceforge.net/license.txt

